# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masternode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='masternode.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10masternode.proto\"c\n\x10\x43ognitionRequest\x12\x1f\n\x17\x61rchitectureFileAddress\x18\x01 \x01(\t\x12\x18\n\x10modelFileAddress\x18\x02 \x01(\t\x12\x14\n\x0csamplesCount\x18\x03 \x01(\r\"9\n\x11\x43ognitionResponse\x12\x0e\n\x06taskID\x18\x01 \x01(\t\x12\x14\n\x0ctimeEstimate\x18\x02 \x01(\r\"I\n\x0f\x43ognitionResult\x12\x1a\n\x12resultsFileAddress\x18\x01 \x01(\t\x12\x14\n\x0csamplesCount\x18\x02 \x01(\rJ\x04\x08\x03\x10\x05\"\"\n\x0f\x43ognitionStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32H\n\rWorkerService\x12\x37\n\x0c\x43ogniteBatch\x12\x11.CognitionRequest\x1a\x12.CognitionResponse\"\x00\x32N\n\x11MasternodeSerivce\x12\x39\n\x11\x63ognitionComplete\x12\x10.CognitionResult\x1a\x10.CognitionStatus\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COGNITIONREQUEST = _descriptor.Descriptor(
  name='CognitionRequest',
  full_name='CognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='architectureFileAddress', full_name='CognitionRequest.architectureFileAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelFileAddress', full_name='CognitionRequest.modelFileAddress', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samplesCount', full_name='CognitionRequest.samplesCount', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=119,
)


_COGNITIONRESPONSE = _descriptor.Descriptor(
  name='CognitionResponse',
  full_name='CognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskID', full_name='CognitionResponse.taskID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeEstimate', full_name='CognitionResponse.timeEstimate', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=178,
)


_COGNITIONRESULT = _descriptor.Descriptor(
  name='CognitionResult',
  full_name='CognitionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultsFileAddress', full_name='CognitionResult.resultsFileAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samplesCount', full_name='CognitionResult.samplesCount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=253,
)


_COGNITIONSTATUS = _descriptor.Descriptor(
  name='CognitionStatus',
  full_name='CognitionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CognitionStatus.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=289,
)

DESCRIPTOR.message_types_by_name['CognitionRequest'] = _COGNITIONREQUEST
DESCRIPTOR.message_types_by_name['CognitionResponse'] = _COGNITIONRESPONSE
DESCRIPTOR.message_types_by_name['CognitionResult'] = _COGNITIONRESULT
DESCRIPTOR.message_types_by_name['CognitionStatus'] = _COGNITIONSTATUS

CognitionRequest = _reflection.GeneratedProtocolMessageType('CognitionRequest', (_message.Message,), dict(
  DESCRIPTOR = _COGNITIONREQUEST,
  __module__ = 'masternode_pb2'
  # @@protoc_insertion_point(class_scope:CognitionRequest)
  ))
_sym_db.RegisterMessage(CognitionRequest)

CognitionResponse = _reflection.GeneratedProtocolMessageType('CognitionResponse', (_message.Message,), dict(
  DESCRIPTOR = _COGNITIONRESPONSE,
  __module__ = 'masternode_pb2'
  # @@protoc_insertion_point(class_scope:CognitionResponse)
  ))
_sym_db.RegisterMessage(CognitionResponse)

CognitionResult = _reflection.GeneratedProtocolMessageType('CognitionResult', (_message.Message,), dict(
  DESCRIPTOR = _COGNITIONRESULT,
  __module__ = 'masternode_pb2'
  # @@protoc_insertion_point(class_scope:CognitionResult)
  ))
_sym_db.RegisterMessage(CognitionResult)

CognitionStatus = _reflection.GeneratedProtocolMessageType('CognitionStatus', (_message.Message,), dict(
  DESCRIPTOR = _COGNITIONSTATUS,
  __module__ = 'masternode_pb2'
  # @@protoc_insertion_point(class_scope:CognitionStatus)
  ))
_sym_db.RegisterMessage(CognitionStatus)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class WorkerServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.CogniteBatch = channel.unary_unary(
          '/WorkerService/CogniteBatch',
          request_serializer=CognitionRequest.SerializeToString,
          response_deserializer=CognitionResponse.FromString,
          )


  class WorkerServiceServicer(object):

    def CogniteBatch(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CogniteBatch': grpc.unary_unary_rpc_method_handler(
            servicer.CogniteBatch,
            request_deserializer=CognitionRequest.FromString,
            response_serializer=CognitionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class MasternodeSerivceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.cognitionComplete = channel.unary_unary(
          '/MasternodeSerivce/cognitionComplete',
          request_serializer=CognitionResult.SerializeToString,
          response_deserializer=CognitionStatus.FromString,
          )


  class MasternodeSerivceServicer(object):

    def cognitionComplete(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_MasternodeSerivceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'cognitionComplete': grpc.unary_unary_rpc_method_handler(
            servicer.cognitionComplete,
            request_deserializer=CognitionResult.FromString,
            response_serializer=CognitionStatus.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'MasternodeSerivce', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaWorkerServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def CogniteBatch(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaWorkerServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def CogniteBatch(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    CogniteBatch.future = None


  def beta_create_WorkerService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('WorkerService', 'CogniteBatch'): CognitionRequest.FromString,
    }
    response_serializers = {
      ('WorkerService', 'CogniteBatch'): CognitionResponse.SerializeToString,
    }
    method_implementations = {
      ('WorkerService', 'CogniteBatch'): face_utilities.unary_unary_inline(servicer.CogniteBatch),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_WorkerService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('WorkerService', 'CogniteBatch'): CognitionRequest.SerializeToString,
    }
    response_deserializers = {
      ('WorkerService', 'CogniteBatch'): CognitionResponse.FromString,
    }
    cardinalities = {
      'CogniteBatch': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'WorkerService', cardinalities, options=stub_options)


  class BetaMasternodeSerivceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def cognitionComplete(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaMasternodeSerivceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def cognitionComplete(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    cognitionComplete.future = None


  def beta_create_MasternodeSerivce_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('MasternodeSerivce', 'cognitionComplete'): CognitionResult.FromString,
    }
    response_serializers = {
      ('MasternodeSerivce', 'cognitionComplete'): CognitionStatus.SerializeToString,
    }
    method_implementations = {
      ('MasternodeSerivce', 'cognitionComplete'): face_utilities.unary_unary_inline(servicer.cognitionComplete),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_MasternodeSerivce_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('MasternodeSerivce', 'cognitionComplete'): CognitionResult.SerializeToString,
    }
    response_deserializers = {
      ('MasternodeSerivce', 'cognitionComplete'): CognitionStatus.FromString,
    }
    cardinalities = {
      'cognitionComplete': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'MasternodeSerivce', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
