@startuml

package connectors {
    class EthConnected
    class IPFSConnected
}

package stdlib #lightgrey {
    class Thread
}

package patterns {
    class StateMachine
    class Singleton
}

package node {
    class WorkerNode
    enum NodeStates {
    }
    WorkerNode -- NodeStates
    EthConnected <|-- WorkerNode
    StateMachine <|-- WorkerNode
    Thread <|-- WorkerNode
}

package job {
    class CognitiveJob
    enum JobStates {
    }
    CognitiveJob -- JobStates
    EthConnected <|-- CognitiveJob
    StateMachine <|-- CognitiveJob
    Thread <|-- CognitiveJob
}

package processor {
    class Processor
    enum ProcessorStates {
    }
    Processor -- ProcessorStates
    Thread <|-- Processor
    IPFSConnected <|-- Processor
    StateMachine <|-- Processor
}

package webapi {
    class WebAPIServer
    Thread <|-- WebAPIServer
}

class Broker
Singleton <|-- Broker
Broker *--o WorkerNode
Broker *--o WebAPIServer
CognitiveJob *--o WorkerNode

@enduml