@startuml
skinparam componentStyle uml2

package Thread1 {
    () "Worker Node\nContract" << Web3 >> as workerContract
    [WorkerNode]
    [WorkerNode] <-left- workerContract

    note bottom of [WorkerNode]
        State reflects
        WorkerNode
        contract state
    end note
}

package Thread2 {
    () "Admin Web API" << JSON-RPC >> as webAPI
    [WebAPI]
    [WebAPI] <-right- webAPI
}

package Thread3 {
    () "Cognitive Job\nContract" << Web3 >> as jobContract
    [CognitiveJob]
    [CognitiveJob] <-left- jobContract

    note bottom of [CognitiveJob]
        State reflects
        CognitiveJob
        contract state
    end note
}

package Thread0 {
    [Broker]
}

package Thread5 {
    () IPFS
    [Processor]
    [Keras]
    [Kernel]
    [Dataset]
    [Processor] --> [Keras]
    [Processor] --> [Kernel]
    [Processor] --> [Dataset]
    [Kernel] --> IPFS
    [Dataset] --> IPFS
}

[Broker] <.right. [WebAPI]
[Broker] <.up.> [WorkerNode]
[Broker] <..> [CognitiveJob]
[Broker] <..> [Processor]

@enduml